In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier as GBC 
from sklearn.model_selection import train_test_split as tts
from sklearn.model_selection import KFold
from imblearn.over_sampling import SMOTE
from sklearn.metrics import *
import random

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [3]:
df = pd.read_csv('gdrive/MyDrive/NewThesis_Poonyawat_Woottisart/Dataset/rgb_img_dataset_test.csv')

In [4]:
df = df.drop('filename', axis=1)

In [5]:
df

r_range_1 g_range_1 b_range_1  ...  b_range_7 proportion_7 label
0       16-31     16-31     16-31  ...     96-111     0.018866     0
1       16-31     16-31     16-31  ...    208-223     0.028382     0
2     224-239   224-239   224-239  ...      64-79     0.038894     0
3       32-47     32-47     48-63  ...      64-79     0.032069     0
4        0-15      0-15      0-15  ...       0-15     0.035422     0
..        ...       ...       ...  ...        ...          ...   ...
605     16-31      0-15      0-15  ...      80-95     0.015809     0
606     32-47     32-47     32-47  ...      48-63     0.024403     0
607   128-143   112-127     64-79  ...      32-47     0.022496     0
608      0-15     32-47     32-47  ...      48-63     0.024963     0
609      0-15      0-15     80-95  ...    112-127     0.035268     0

[610 rows x 29 columns]

In [6]:
def convert_range_to_order(val):
    result = int(val.split('-')[0])/16
    return int(result)

In [7]:
for col_name in df.columns:
    if('_range_' in col_name):
        df[col_name] = df[col_name].apply(lambda x: convert_range_to_order(x))

In [8]:
df

r_range_1  g_range_1  b_range_1  ...  b_range_7  proportion_7  label
0            1          1          1  ...          6      0.018866      0
1            1          1          1  ...         13      0.028382      0
2           14         14         14  ...          4      0.038894      0
3            2          2          3  ...          4      0.032069      0
4            0          0          0  ...          0      0.035422      0
..         ...        ...        ...  ...        ...           ...    ...
605          1          0          0  ...          5      0.015809      0
606          2          2          2  ...          3      0.024403      0
607          8          7          4  ...          2      0.022496      0
608          0          2          2  ...          3      0.024963      0
609          0          0          5  ...          7      0.035268      0

[610 rows x 29 columns]

In [9]:
df['label'].value_counts()

0    456
1    154
Name: label, dtype: int64

In [10]:
def model_training(df, training_size, param): 
    # training_size is ratio of training data for train-test split (float)
    # param is set of parameter for model training (dict)
    
    X = df.drop('label', axis=1)
    y = df['label']
    X_train, X_test, y_train, y_test = tts(X, y, train_size=training_size, random_state=42)
    
    sm = SMOTE(sampling_strategy = 1, random_state=42)
    X_res, y_res = sm.fit_resample(X_train, y_train.ravel())
    
    clf = GBC(max_depth=param['max_depth'], 
              criterion=param['criterion'],
              min_impurity_decrease=param['min_impurity_decrease'], random_state=42).fit(X_res, y_res)
    # clf = GBC(set_of_parameter)
    y_pred = clf.predict(X_test)
    
    print('Confusion Matrix')
    print(confusion_matrix(y_test, y_pred))
    print('Accuracy: {:.4f}'.format(accuracy_score(y_test, y_pred)))
    print('Precision: {:.4f}'.format(precision_score(y_test, y_pred)))
    print('Recall: {:.4f}'.format(recall_score(y_test, y_pred)))
    
    return clf

In [15]:
def random_parameter(param_name):
    
    if(param_name=='max_depth'):
        return random.randint(1, 10)
    
    if(param_name=='criterion'):
        tmp = random.randint(1, 2)
        if(tmp==1):
            return 'friedman_mse'
        elif(tmp==2):
            return 'mae'
            
    if(param_name=='min_impurity_decrease'):
        return random.random()/10

In [16]:
param = {'max_depth': random_parameter('max_depth'),
         'criterion': random_parameter('criterion'),
         'min_impurity_decrease': random_parameter('min_impurity_decrease')}

In [17]:
model = model_training(df, 0.75, param)

Confusion Matrix
[[66 51]
 [ 7 29]]
Accuracy: 0.6209
Precision: 0.3625
Recall: 0.8056


/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:475: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py:363: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py:363: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py:363: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py:363: FutureWarning: C

In [18]:
for i in range(5):
    param = {'max_depth': random_parameter('max_depth'),
             'criterion': random_parameter('criterion'),
             'min_impurity_decrease': random_parameter('min_impurity_decrease')}
    model = model_training(df, 0.75, param)

/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:475: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py:363: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py:363: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py:363: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,


Confusion Matrix
[[117   0]
 [ 36   0]]
Accuracy: 0.7647
Precision: 0.0000
Recall: 0.0000


/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py:363: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py:363: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py:363: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py:363: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py:363: FutureWarning: 

Confusion Matrix
[[91 26]
 [15 21]]
Accuracy: 0.7320
Precision: 0.4468
Recall: 0.5833
Confusion Matrix
[[91 26]
 [15 21]]
Accuracy: 0.7320
Precision: 0.4468
Recall: 0.5833
Confusion Matrix
[[95 22]
 [11 25]]
Accuracy: 0.7843
Precision: 0.5319
Recall: 0.6944
Confusion Matrix
[[66 51]
 [ 7 29]]
Accuracy: 0.6209
Precision: 0.3625
Recall: 0.8056


/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:475: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py:363: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py:363: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py:363: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py:363: FutureWarning: C